server:
  port: 8081
  servlet:
    context-path: /student-service

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-student.html

management:
  endpoints:
    web:
      exposure:
        include: '*'